# Generated by Django 4.1.5 on 2023-01-19 10:29

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=django_minio_backend.models.MinioBackend(backend_name='media'), upload_to=django_minio_backend.models.iso_date_prefix)),
            ],
        ),
    ]
